### ISSUE TITLE
Cannot handle more than 10 colors

### ISSUE THREAD

**Issue by vwxyzjn** [wookayin/expt#23]
https://github.com/wookayin/expt/blob/b2539fbb210e35c3a44976af342956db2b836df3/expt/plot.py#L936

The `axes_props` in the snippet above apparently creates the same reference dict after 10 colors

```
(Pdb) [id(item) for item in axes_props]
[5819315328, 5820116160, 5820114688, 5820113216, 5791326080, 5819699392, 5819702144, 5820000640, 5819999296, 5819495744, 5819315328]
```

As a result, plotting more than ten colors is not possible.

<img width="594" alt="image" src="https://github.com/wookayin/expt/assets/5555347/1f84ce2a-f2d8-44f3-80ca-4097d405ae46">

To fix it, I just added

```
    import copy
    axes_props = [copy.deepcopy(prop) for prop in axes_props]
```

which fixes the issue.

<img width="594" alt="image" src="https://github.com/wookayin/expt/assets/5555347/71739fe2-970c-4b3c-9d70-60bc0794e572">

**Comment by wookayin** [comment]
Thank you @vwxyzjn for reporting this issue. I actually see the two screenshots you attached are identical. Maybe the former one has limited colors?

As a side note, expt by default uses the default ten matplotlib's default colors, you can change the underlying property cycle. So for example: 

```
colors: List[str] = expt.colors.DefaultColors  # 17 colors, for example
plt.rcParams["axes.prop_cycle"] = plt.cycler("color", colors)
```

or you can choose any palette or colormaps (https://matplotlib.org/stable/tutorials/colors/colormaps.html).

I think the API for dealing with colors and other cycling props are not quite handy. Let me make some improvements in some near future.
